# 项目名称
project_name: 项目名称

# 环境
env: 测试环境

# 测试人员名称
tester_name: Hrenny

# 域名
host: https://www.wanandroid.com
app_host:

# 实时更新用例内容，false时，已生成的代码不会在做变更
# 设置True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

# 报告通知类型：0：不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 0

# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持发送企业微信通知
ding_talk:
  webhook:
  secret:
# 数据库相关配置
mysql_db:
  # 数据库开关
  switch: False
  host:
  user: root
  password: '123456'
  port: 3306

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
wechat:
  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22748687-fa3b-4e48-a5d7-0502cef422b4

# 配置邮箱
email:
  send_user:
  email_host: smtp.qq.com
  stamp_key:
  # 收件人
  send_list:

# 飞书通知
lark:
  webhook: